---

- block:
    - name: Install packages with yarn
      ansible.builtin.shell:
        cmd: yarn
        chdir: "{{ build_dir }}"

    - name: Build with yarn
      ansible.builtin.shell:
        cmd: yarn build
        chdir: "{{ build_dir }}"

  become: yes
  become_user: "{{ xo.user.name }}"
