---

- block:
    - name: Remove node_modules directory
      ansible.builtin.file:
        path: "{{ build_dir }}/node_modules"
        state: absent

    - name: Build with yarn
      ansible.builtin.shell:
        cmd: |-
          yarn && yarn build
        chdir: "{{ build_dir }}"
  become: yes
  become_user: "{{ xo.user.name }}"
