---

- name: "Trim previous configs"
  ansible.builtin.shell:
    cmd: find .config -type f -name config.toml* # TODO
    chdir: "{{ xo.user.home }}"
  become: yes
  become_user: "{{ xo.user.name }}"
