---

# https://xen-orchestra.com/docs/installation.html#from-the-sources
- name: Install dependencies
  ansible.builtin.apt:
    pkg:
      - build-essential
      - cifs-utils
      - git
      - libpng-dev
      - libvhdi-utils
      - lvm2
      - python3-minimal
      - redis-server
      - sudo
      - authbind
      - vim-nox
      - net-tools
      - curl

- name: Enable corepack (and thus yarn as a result)
  ansible.builtin.shell:
    cmd: corepack enable
  changed_when: false

- name: Ensure that yarn exists in $PATH
  ansible.builtin.shell:
    cmd: which yarn
  changed_when: false
  register: r
  failed_when: r.rc != 0
